const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.TileMovement,
		C3.Behaviors.Pin,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Behaviors.Tween,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.TileMovement.Cnds.IsMovingDirection,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.TileMovement.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.TileMovement.Acts.SetSpeed,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{SolidTilemap: 0},
	{LayerTilemap: 0},
	{BackgroundTilemap: 0},
	{Tilemap: 0},
	{Tilemap2: 0},
	{startMap: 0},
	{TileMovement: 0},
	{Player_Box: 0},
	{Direction: 0},
	{Pin: 0},
	{ScrollTo: 0},
	{Player_Mask: 0},
	{EdgeBarrier: 0},
	{Keyboard: 0},
	{Audio: 0},
	{isCounted: 0},
	{Tree: 0},
	{Tree2: 0},
	{Yarn: 0},
	{Fish: 0},
	{Milk: 0},
	{GodTree: 0},
	{Timer: 0},
	{Inventory: 0},
	{isFull: 0},
	{container: 0},
	{Bullet: 0},
	{bullet: 0},
	{bulletSpawn: 0},
	{Title: 0},
	{startButton: 0},
	{animatedWater: 0},
	{Mouse: 0},
	{Begin: 0},
	{Sprite2: 0},
	{Tween: 0},
	{FadeToBlack: 0},
	{arrowKeys: 0},
	{magic: 0},
	{meow: 0},
	{ManaBar: 0},
	{Score: 0},
	{Sprite: 0},
	{Sprite3: 0},
	{unknownName: 0},
	{introDialog0: 0},
	{powerupText: 0},
	{blueFlower: 0},
	{redFlower: 0},
	{continue: 0},
	{Pickups: 0},
	{currentMana: 0},
	{isRegen: 0},
	{maxMana: 0},
	{manaRegenTime: 0},
	{hits: 0},
	{score: 0},
	{timer: 0},
	{powerUp0: 0},
	{powerUp1: 0},
	{onlyOnce: 0},
	{Parameter0: 0},
	{dialogIndex: 0},
	{dialogCount: 0},
	{dialogLine0: 0},
	{dialogLine1: 0},
	{dialogLine2: 0},
	{dialogLine3: 0},
	{continueLine: 0},
	{dialogIndexOutro: 0},
	{dialogCountOutro: 0},
	{dialogLine0_Outro: 0},
	{dialogLine1_Outro: 0},
	{dialogLine2_Outro: 0},
	{dialogLine3_Outro: 0}
];

self.InstanceType = {
	SolidTilemap: class extends self.ITilemapInstance {},
	LayerTilemap: class extends self.ITilemapInstance {},
	BackgroundTilemap: class extends self.ITilemapInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	startMap: class extends self.ITilemapInstance {},
	Player_Box: class extends self.ISpriteInstance {},
	Player_Mask: class extends self.ISpriteInstance {},
	EdgeBarrier: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Tree: class extends self.ISpriteInstance {},
	Tree2: class extends self.ISpriteInstance {},
	Yarn: class extends self.ISpriteInstance {},
	Fish: class extends self.ISpriteInstance {},
	Milk: class extends self.ISpriteInstance {},
	GodTree: class extends self.ISpriteInstance {},
	Timer: class extends self.ISpriteInstance {},
	Inventory: class extends self.ISpriteInstance {},
	container: class extends self.ISpriteInstance {},
	bullet: class extends self.ISpriteInstance {},
	bulletSpawn: class extends self.ISpriteInstance {},
	Title: class extends self.ITextInstance {},
	startButton: class extends self.ISpriteInstance {},
	animatedWater: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Begin: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	FadeToBlack: class extends self.ISpriteInstance {},
	arrowKeys: class extends self.ITextInstance {},
	magic: class extends self.ITextInstance {},
	meow: class extends self.ITextInstance {},
	ManaBar: class extends self.ISpriteInstance {},
	Score: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	unknownName: class extends self.ITextInstance {},
	introDialog0: class extends self.ITextInstance {},
	powerupText: class extends self.ITextInstance {},
	blueFlower: class extends self.ISpriteInstance {},
	redFlower: class extends self.ISpriteInstance {},
	continue: class extends self.ITextInstance {},
	Pickups: class extends self.ISpriteInstance {}
}